[project]
name = "metadata"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.NFT]
path = "contracts/NFT.clar"
depends_on = []
